In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import warnings

warnings.filterwarnings('ignore')

<h1>Load Dataset</h1>

In [6]:
df = pd.read_csv("C:\\Uni\\Semester 6\\Data Visiualization\\Data-Visualization-Project\\data\\owid-energy-raw-data.csv")

df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

<h1>Shape + Columns</h1>

In [ ]:
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (23377, 130)

Columns:
['country', 'year', 'iso_code', 'population', 'gdp', 'biofuel_cons_change_pct', 'biofuel_cons_change_twh', 'biofuel_cons_per_capita', 'biofuel_consumption', 'biofuel_elec_per_capita', 'biofuel_electricity', 'biofuel_share_elec', 'biofuel_share_energy', 'carbon_intensity_elec', 'coal_cons_change_pct', 'coal_cons_change_twh', 'coal_cons_per_capita', 'coal_consumption', 'coal_elec_per_capita', 'coal_electricity', 'coal_prod_change_pct', 'coal_prod_change_twh', 'coal_prod_per_capita', 'coal_production', 'coal_share_elec', 'coal_share_energy', 'electricity_demand', 'electricity_demand_per_capita', 'electricity_generation', 'electricity_share_energy', 'energy_cons_change_pct', 'energy_cons_change_twh', 'energy_per_capita', 'energy_per_gdp', 'fossil_cons_change_pct', 'fossil_cons_change_twh', 'fossil_elec_per_capita', 'fossil_electricity', 'fossil_energy_per_capita', 'fossil_fuel_consumption', 'fossil_share_elec', 'fossil_share_energy', 'gas_cons_change_pct', 'gas_cons_change_twh', 'gas_consumption', 'gas_elec_per_capita', 'gas_electricity', 'gas_energy_per_capita', 'gas_prod_change_pct', 'gas_prod_change_twh', 'gas_prod_per_capita', 'gas_production', 'gas_share_elec', 'gas_share_energy', 'greenhouse_gas_emissions', 'hydro_cons_change_pct', 'hydro_cons_change_twh', 'hydro_consumption', 'hydro_elec_per_capita', 'hydro_electricity', 'hydro_energy_per_capita', 'hydro_share_elec', 'hydro_share_energy', 'low_carbon_cons_change_pct', 'low_carbon_cons_change_twh', 'low_carbon_consumption', 'low_carbon_elec_per_capita', 'low_carbon_electricity', 'low_carbon_energy_per_capita', 'low_carbon_share_elec', 'low_carbon_share_energy', 'net_elec_imports', 'net_elec_imports_share_demand', 'nuclear_cons_change_pct', 'nuclear_cons_change_twh', 'nuclear_consumption', 'nuclear_elec_per_capita', 'nuclear_electricity', 'nuclear_energy_per_capita', 'nuclear_share_elec', 'nuclear_share_energy', 'oil_cons_change_pct', 'oil_cons_change_twh', 'oil_consumption', 'oil_elec_per_capita', 'oil_electricity', 'oil_energy_per_capita', 'oil_prod_change_pct', 'oil_prod_change_twh', 'oil_prod_per_capita', 'oil_production', 'oil_share_elec', 'oil_share_energy', 'other_renewable_consumption', 'other_renewable_electricity', 'other_renewable_exc_biofuel_electricity', 'other_renewables_cons_change_pct', 'other_renewables_cons_change_twh', 'other_renewables_elec_per_capita', 'other_renewables_elec_per_capita_exc_biofuel', 'other_renewables_energy_per_capita', 'other_renewables_share_elec', 'other_renewables_share_elec_exc_biofuel', 'other_renewables_share_energy', 'per_capita_electricity', 'primary_energy_consumption', 'renewables_cons_change_pct', 'renewables_cons_change_twh', 'renewables_consumption', 'renewables_elec_per_capita', 'renewables_electricity', 'renewables_energy_per_capita', 'renewables_share_elec', 'renewables_share_energy', 'solar_cons_change_pct', 'solar_cons_change_twh', 'solar_consumption', 'solar_elec_per_capita', 'solar_electricity', 'solar_energy_per_capita', 'solar_share_elec', 'solar_share_energy', 'wind_cons_change_pct', 'wind_cons_change_twh', 'wind_consumption', 'wind_elec_per_capita', 'wind_electricity', 'wind_energy_per_capita', 'wind_share_elec', 'wind_share_energy']
Number of Columns: 130

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23377 entries, 0 to 23376
Columns: 130 entries, country to wind_share_energy
dtypes: float64(127), int64(1), str(2)
memory usage: 23.2 MB

In [13]:
df.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,23377.000000,1.889400e+04,1.178000e+04,2070.000000,7903.000000,6338.000000,8057.000000,6015.000000,6337.000000,6311.000000,...,7869.000000,6379.000000,2798.000000,6293.000000,6405.000000,8405.000000,9507.000000,5145.000000,7661.000000,6379.000000
mean,1976.238611,1.058587e+08,4.257565e+11,43.478821,1.054261,55.157110,15.092053,70.470840,12.503951,1.961657,...,1.115397,0.219811,290.408295,6.021235,48.691258,70.093753,21.368874,214.958756,1.712025,0.518142
std,35.331092,4.720948e+08,3.507870e+12,286.672304,6.641947,180.660546,75.942537,200.084733,53.260917,5.353897,...,3.337844,0.766123,6070.498588,34.260035,281.755752,277.601211,127.539439,733.879405,4.962740,1.722173
min,1900.000000,1.776000e+03,1.642060e+08,-100.000000,-59.083984,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-100.000000,-46.534790,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1949.000000,1.599088e+06,1.426394e+10,-0.968287,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,2.328556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1985.000000,6.951653e+06,4.357680e+10,6.695433,0.000000,0.000000,0.000000,0.875653,0.020000,0.153061,...,0.000000,0.000000,18.349456,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2005.000000,2.581793e+07,1.830576e+11,23.320313,0.000000,0.506788,0.061667,44.131332,0.880000,1.600195,...,0.294424,0.005892,45.211092,0.095950,0.915601,2.195791,0.133600,25.914005,0.629577,0.074523
max,2025.000000,8.231613e+09,1.301126e+14,6373.061523,144.289948,2587.707520,1366.878296,2450.790527,710.409973,77.586205,...,50.000000,9.881398,242384.859375,642.616699,6124.465332,4015.415771,2713.139893,9315.287109,58.214485,26.085308

<h1>Missing Values Analysis</h1>

In [11]:
missing_values = df.isnull().sum().sort_values(ascending=False)

missing_percent = (
    df.isnull().sum() / len(df) * 100
).sort_values(ascending=False)

missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percent
})

missing_df.head(20)

,Missing Values,Missing Percentage
biofuel_cons_change_pct,21307,91.145143
solar_cons_change_pct,20862,89.241562
nuclear_cons_change_pct,20798,88.967789
wind_cons_change_pct,20579,88.030971
other_renewables_cons_change_pct,19389,82.940497
electricity_share_energy,19274,82.448561
low_carbon_energy_per_capita,18232,77.991188
oil_energy_per_capita,18232,77.991188
coal_cons_per_capita,18232,77.991188
fossil_energy_per_capita,18232,77.991188
gas_energy_per_capita,18232,77.991188
hydro_energy_per_capita,18232,77.991188
other_renewables_energy_per_capita,18232,77.991188
renewables_energy_per_capita,18232,77.991188
solar_energy_per_capita,18232,77.991188
wind_energy_per_capita,18232,77.991188
other_renewables_elec_per_capita_exc_biofuel,17983,76.926038
gas_cons_change_pct,17734,75.860889
hydro_cons_change_pct,17691,75.676947
other_renewables_share_elec_exc_biofuel,17687,75.659837

<h1>Drop High Missing Columns</h1>

In [14]:
threshold = 0.7

missing_ratio = df.isnull().mean()

columns_to_drop = missing_ratio[
    missing_ratio > threshold
].index

df_clean = df.drop(columns=columns_to_drop)

print("Removed Columns:", len(columns_to_drop))
print("New Shape:", df_clean.shape)

Removed Columns: 74
New Shape: (23377, 56)

<h1>Fill Missing Values</h1>

In [16]:
df.isnull().sum()

country                       0
year                          0
iso_code                   6112
population                 4483
gdp                       11597
                          ...
wind_elec_per_capita      14972
wind_electricity          13870
wind_energy_per_capita    18232
wind_share_elec           15716
wind_share_energy         16998
Length: 130, dtype: int64

In [15]:
# Numeric columns
numeric_cols = df_clean.select_dtypes(
    include=np.number
).columns

df_clean[numeric_cols] = df_clean[numeric_cols].fillna(
    df_clean[numeric_cols].median()
)

# Categorical columns
categorical_cols = df_clean.select_dtypes(
    include="object"
).columns

for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna(
        df_clean[col].mode()[0]
    )

df_clean.isnull().sum().sum()

np.int64(0)

<h1>Remove Duplicates</h>

In [17]:
duplicates = df_clean.duplicated().sum()

print("Duplicate Rows:", duplicates)

df_clean = df_clean.drop_duplicates()

print(
    "Shape After Removing Duplicates:",
    df_clean.shape
)

Duplicate Rows: 0
Shape After Removing Duplicates: (23377, 56)

<h1>Keep Countries Only</h1>

In [18]:
df_countries = df_clean[
    df_clean["iso_code"].notnull()
].copy()

print(df_countries.shape)

df_countries.head()

(23377, 56)

,country,year,iso_code,population,gdp,biofuel_cons_change_twh,biofuel_consumption,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,...,primary_energy_consumption,renewables_elec_per_capita,renewables_electricity,renewables_share_elec,solar_elec_per_capita,solar_electricity,solar_share_elec,wind_elec_per_capita,wind_electricity,wind_share_elec
0,ASEAN (Ember),2000,ARG,6951653.0,4.357680e+10,0.0,0.0,76.029999,2.22249,0.0,...,91.18718,219.620468,73.230003,19.334143,0.0,0.0,0.0,0.0,0.0,0.0
1,ASEAN (Ember),2001,ARG,6951653.0,4.357680e+10,0.0,0.0,86.260002,2.22249,0.0,...,91.18718,219.620468,77.190002,19.055025,0.0,0.0,0.0,0.0,0.0,0.0
2,ASEAN (Ember),2002,ARG,6951653.0,4.357680e+10,0.0,0.0,93.430000,2.22249,0.0,...,91.18718,219.620468,76.529999,17.666613,0.0,0.0,0.0,0.0,0.0,0.0
3,ASEAN (Ember),2003,ARG,6951653.0,4.357680e+10,0.0,0.0,102.010002,2.22249,0.0,...,91.18718,219.620468,76.389999,16.668121,0.0,0.0,0.0,0.0,0.0,0.0
4,ASEAN (Ember),2004,ARG,6951653.0,4.357680e+10,0.0,0.0,115.010002,2.22249,0.0,...,91.18718,219.620468,77.949997,15.696422,0.0,0.0,0.0,0.0,0.0,0.0

<h1>Select Important Columns</h1>

In [20]:
selected_columns = [
    "country",
    "year",
    "population",
    "gdp",
    "coal_consumption",
    "oil_consumption",
    "gas_consumption",
    "solar_consumption",
    "wind_consumption",
    "renewables_consumption",
    "fossil_fuel_consumption",
    "electricity_generation"
]

# Keep only columns that actually exist
existing_columns = [
    col for col in selected_columns
    if col in df_countries.columns
]

print("Existing Columns:")
print(existing_columns)

viz_df = df_countries[existing_columns].copy()

viz_df.head()

Existing Columns:
['country', 'year', 'population', 'gdp', 'electricity_generation']

         country  year  population           gdp  electricity_generation
0  ASEAN (Ember)  2000   6951653.0  4.357680e+10              378.760010
1  ASEAN (Ember)  2001   6951653.0  4.357680e+10              405.089996
2  ASEAN (Ember)  2002   6951653.0  4.357680e+10              433.190002
3  ASEAN (Ember)  2003   6951653.0  4.357680e+10              458.299988
4  ASEAN (Ember)  2004   6951653.0  4.357680e+10              496.609985

In [21]:
print(df_countries.columns.tolist())

['country', 'year', 'iso_code', 'population', 'gdp', 'biofuel_cons_change_twh', 'biofuel_consumption', 'coal_electricity', 'coal_prod_change_pct', 'coal_prod_change_twh', 'coal_prod_per_capita', 'coal_production', 'coal_share_elec', 'electricity_generation', 'energy_cons_change_pct', 'energy_cons_change_twh', 'energy_per_capita', 'energy_per_gdp', 'fossil_electricity', 'fossil_share_elec', 'gas_electricity', 'gas_prod_change_pct', 'gas_prod_change_twh', 'gas_prod_per_capita', 'gas_production', 'hydro_elec_per_capita', 'hydro_electricity', 'hydro_share_elec', 'low_carbon_elec_per_capita', 'low_carbon_electricity', 'low_carbon_share_elec', 'nuclear_cons_change_twh', 'nuclear_consumption', 'nuclear_elec_per_capita', 'nuclear_electricity', 'nuclear_share_elec', 'oil_electricity', 'oil_prod_change_pct', 'oil_prod_change_twh', 'oil_prod_per_capita', 'oil_production', 'oil_share_elec', 'other_renewable_electricity', 'other_renewables_elec_per_capita', 'other_renewables_share_elec', 'per_capita_electricity', 'primary_energy_consumption', 'renewables_elec_per_capita', 'renewables_electricity', 'renewables_share_elec', 'solar_elec_per_capita', 'solar_electricity', 'solar_share_elec', 'wind_elec_per_capita', 'wind_electricity', 'wind_share_elec']

<h1>Create Decade Column</h1>

In [22]:
viz_df["decade"] = (
    viz_df["year"] // 10
) * 10

viz_df.head()

,country,year,population,gdp,electricity_generation,decade
0,ASEAN (Ember),2000,6951653.0,4.357680e+10,378.760010,2000
1,ASEAN (Ember),2001,6951653.0,4.357680e+10,405.089996,2000
2,ASEAN (Ember),2002,6951653.0,4.357680e+10,433.190002,2000
3,ASEAN (Ember),2003,6951653.0,4.357680e+10,458.299988,2000
4,ASEAN (Ember),2004,6951653.0,4.357680e+10,496.609985,2000

<h1>Clean Country Names</h1>

In [23]:
viz_df["country"] = (
    viz_df["country"]
    .str.strip()
    .str.title()
)

viz_df.head()

,country,year,population,gdp,electricity_generation,decade
0,Asean (Ember),2000,6951653.0,4.357680e+10,378.760010,2000
1,Asean (Ember),2001,6951653.0,4.357680e+10,405.089996,2000
2,Asean (Ember),2002,6951653.0,4.357680e+10,433.190002,2000
3,Asean (Ember),2003,6951653.0,4.357680e+10,458.299988,2000
4,Asean (Ember),2004,6951653.0,4.357680e+10,496.609985,2000

<h1>Outlier Detection</h1>

In [24]:
numeric_viz = viz_df.select_dtypes(
    include=np.number
)

Q1 = numeric_viz.quantile(0.25)
Q3 = numeric_viz.quantile(0.75)

IQR = Q3 - Q1

outliers = (
    (
        numeric_viz < (Q1 - 1.5 * IQR)
    ) |
    (
        numeric_viz > (Q3 + 1.5 * IQR)
    )
).sum()

outliers.sort_values(
    ascending=False
).head(10)

gdp                       11376
electricity_generation     7912
population                 3701
year                          0
decade                        0
dtype: int64

<h1>Export Cleaned CSV</h1>

In [27]:
viz_df.to_csv(
    "owid_energy_visualization_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.